export const COURSEWARE_DETAILS_REQUEST = 'COURSEWARE_DETAILS_REQUEST';
export const COURSEWARE_DETAILS_SUCCESS = 'COURSEWARE_DETAILS_SUCCESS';
export const COURSEWARE_DETAILS_FAIL = 'COURSE_DETAILS_FAIL';

export const COURSEWARE_CREATE_REQUEST = 'COURSEWARE_CREATE_REQUEST';
export const COURSEWARE_CREATE_SUCCESS = 'COURSEWARE_CREATE_SUCCESS';
export const COURSEWARE_CREATE_FAIL = 'COURSEWARE_CREATE_FAIL';
export const COURSEWARE_CREATE_RESET = 'COURSEWARE_CREATE_RESET';

export const COURSEWARE_UPDATE_REQUEST = 'COURSEWARE_UPDATE_REQUEST';
export const COURSEWARE_UPDATE_SUCCESS = 'COURSEWARE_UPDATE_SUCCESS';
export const COURSEWARE_UPDATE_FAIL = 'COURSEWARE_UPDATE_FAIL';
export const COURSEWARE_UPDATE_RESET = 'COURSEWARE_UPDATE_RESET';

export const COURSEWARE_LIST_REQUEST = 'COURSEWARE_LIST_REQUEST';
export const COURSEWARE_LIST_SUCCESS = 'COURSEWARE_LIST_SUCCESS';
export const COURSEWARE_LIST_FAIL = 'COURSEWARE_LIST_FAIL';
export const COURSEWARE_LIST_RESET = 'COURSEWARE_LIST_RESET';
