export const SUBTOPIC_DETAILS_REQUEST = 'SUBTOPIC_DETAILS_REQUEST';
export const SUBTOPIC_DETAILS_SUCCESS = 'SUBTOPIC_DETAILS_SUCCESS';
export const SUBTOPIC_DETAILS_FAIL = 'SUBTOPIC_DETAILS_FAIL';

export const SUBTOPIC_CREATE_REQUEST = 'SUBTOPIC_CREATE_REQUEST';
export const SUBTOPIC_CREATE_SUCCESS = 'SUBTOPIC_CREATE_SUCCESS';
export const SUBTOPIC_CREATE_FAIL = 'SUBTOPIC_CREATE_FAIL';
export const SUBTOPIC_CREATE_RESET = 'SUBTOPIC_CREATE_RESET';

export const SUBTOPIC_UPDATE_REQUEST = 'SUBTOPIC_UPDATE_REQUEST';
export const SUBTOPIC_UPDATE_SUCCESS = 'SUBTOPIC_UPDATE_SUCCESS';
export const SUBTOPIC_UPDATE_FAIL = 'SUBTOPIC_UPDATE_FAIL';
export const SUBTOPIC_UPDATE_RESET = 'SUBTOPIC_UPDATE_RESET';

export const SUBTOPIC_LIST_REQUEST = 'SUBTOPIC_LIST_REQUEST';
export const SUBTOPIC_LIST_SUCCESS = 'SUBTOPIC_LIST_SUCCESS';
export const SUBTOPIC_LIST_FAIL = 'SUBTOPIC_LIST_FAIL';
export const SUBTOPIC_LIST_RESET = 'SUBTOPIC_LIST_RESET';
