export const COURSE_TAUGHT_REQUEST = 'COURSE_TAUGHT_REQUEST';
export const COURSE_TAUGHT_SUCCESS = 'COURSE_TAUGHT_SUCCESS';
export const COURSE_TAUGHT_FAIL = 'COURSE_TAUGHT_FAIL';
export const COURSE_TAUGHT_RESET = 'COURSE_TAUGHT_RESET';
